name = "kyle-portfolio"
main = "./dist/_worker.js/index.js"
compatibility_date = "2025-10-15"
compatibility_flags = [ "nodejs_compat" ]

[assets]
binding = "ASSETS"
directory = "./dist"

[observability]
enabled = true