type ToolType =
    | "TypeScript"
    | "Tailwind"
    | "Next.js"
    | "PostgreSQL"
    | "Redis"
    | "Stripe"
    | "REST"
    | "Vercel"
    | "GraphQL"
    | "Shopify"
    | "MongoDB"
    | "Clerk"
    | "React"
    | "ChakraUI"
    | "HTML"
    | "CSS"
    | "SVG"
    | "Electron"
    | "React Native"
    | "Expo"
    | "SwiftUI"
    | "NodeJS"
    | "Express"
    | "MySQL"
    | "Python"
    | "Supabase"
    | "GoLang"
    | "JWT"
    | "HTTP"
    | "DNS"
    | "SMTP"
    | "S3"
    | "R2"
    | "Java"
    | "Google Cloud"
    | "AWS"
    | "Git"
    | "Docker"
    | "Linux"
    | "Windows"
    | "MacOS"
    | "Nginx"
    | "Jest"
    | "CI/CD"
    | "Figma"
    | "Photoshop"
    | "Illustrator"
    | "Drizzle"
    | "Kafka"
    | "Discord"
    | "Supabase"
    | "Firebase"
    | "Cheerio"
    | "Spotify API"
    | "LLM"
    | "PyTorch"
    | "Brain.js";

export type { ToolType };
